config/routes.rb
Rails.application.routes.draw do
  resources :drops
  root to: "drops#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drop.rb
class Drop < ApplicationRecord
    has_one_attached :file
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/drops_controller.rb
class DropsController < ApplicationController
  before_action :set_drop, only: [:show, :edit, :update, :destroy]

  # GET /drops
  # GET /drops.json
  def index
    @drops = Drop.all
  end

  # GET /drops/1
  # GET /drops/1.json
  def show
  end

  # GET /drops/new
  def new
    @drop = Drop.new
  end

  # GET /drops/1/edit
  def edit
  end

  # POST /drops
  # POST /drops.json
  def create
    @drop = Drop.new(drop_params)

    respond_to do |format|
      if @drop.save
        format.html { redirect_to @drop, notice: 'Drop was successfully created.' }
        format.json { render :show, status: :created, location: @drop }
      else
        format.html { render :new }
        format.json { render json: @drop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drops/1
  # PATCH/PUT /drops/1.json
  def update
    respond_to do |format|
      if @drop.update(drop_params)
        format.html { redirect_to @drop, notice: 'Drop was successfully updated.' }
        format.json { render :show, status: :ok, location: @drop }
      else
        format.html { render :edit }
        format.json { render json: @drop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drops/1
  # DELETE /drops/1.json
  def destroy
    @drop.destroy
    respond_to do |format|
      format.html { redirect_to drops_url, notice: 'Drop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drop
      @drop = Drop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drop_params
      params.require(:drop).permit(:title, :description,:file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drops_helper.rb
module DropsHelper
end

app/views/drops/_form.html.erb
<%= form_with(model: drop, local: true) do |form| %>
  <% if drop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(drop.errors.count, "error") %> prohibited this drop from being saved:</h2>

      <ul>
      <% drop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

   <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/drops/edit.html.erb
<h1>Editing Drop</h1>

<%= render 'form', drop: @drop %>

<%= link_to 'Show', @drop %> |
<%= link_to 'Back', drops_path %>

app/views/drops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Drops</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drops.each do |drop| %>
      <tr>
        <td><%= drop.title %></td>
        <td><%= drop.description %></td>
        <td><%= link_to 'Show', drop %></td>
        <td><%= link_to 'Edit', edit_drop_path(drop) %></td>
        <td><%= link_to 'Destroy', drop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Drop', new_drop_path %>

app/views/drops/new.html.erb
<h1>New Drop</h1>

<%= render 'form', drop: @drop %>

<%= link_to 'Back', drops_path %>

app/views/drops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @drop.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @drop.description %>
</p>

<%= link_to 'View Picture', @drop.file  %>

<%= link_to 'Edit', edit_drop_path(@drop) %> |
<%= link_to 'Back', drops_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Playground</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>